{% set version = "0.6.11" %}

package:
  name: python-pptx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python-pptx/python-pptx-{{ version }}.tar.gz
  sha256: b68b33e0e6cc3ea512c5711651a33f787f18869c3235f2a38b8e46f866bef164

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - lxml >=3.1.0
    - pillow >=2.6.1
    - xlsxwriter >=0.5.7
    - libiconv

test:
  imports:
    - pptx
    - pptx.chart
    - pptx.compat
    - pptx.dml
    - pptx.enum
    - pptx.opc
    - pptx.oxml
    - pptx.oxml.chart
    - pptx.oxml.dml
    - pptx.oxml.shapes
    - pptx.parts
    - pptx.shapes
    - pptx.text

about:
  home: http://github.com/scanny/python-pptx
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Generate and manipulate Open XML PowerPoint (.pptx) files'
  dev_url: http://github.com/scanny/python-pptx
  doc_url: https://python-pptx.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
