{% set name = "python-pptx" %}
{% set version = "0.6.9" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "f1ceec0817ac947dc6fc5599581269693bcc32f666041440bd2ce2a35b40694b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - lxml >=3.1.0
    - pillow >=2.6.1
    - xlsxwriter >=0.5.7

test:
  imports:
    - pptx
    - pptx.chart
    - pptx.compat
    - pptx.dml
    - pptx.enum
    - pptx.opc
    - pptx.oxml
    - pptx.oxml.chart
    - pptx.oxml.dml
    - pptx.oxml.shapes
    - pptx.parts
    - pptx.shapes
    - pptx.text

about:
  home: http://github.com/scanny/python-pptx
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Generate and manipulate Open XML PowerPoint (.pptx) files'
  dev_url: http://github.com/scanny/python-pptx
  doc_url: https://python-pptx.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
