{% set name = "python-pptx" %}
{% set version = "0.6.6" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "b7508d6ab2954854b6efeb2ffc2653ff0e8185fb314df6c8673c534b0caeed50" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - lxml >=3.1.0
    - pillow >=2.6.1
    - xlsxwriter >=0.5.7

test:
  imports:
    - pptx
    - pptx.chart
    - pptx.compat
    - pptx.dml
    - pptx.enum
    - pptx.opc
    - pptx.oxml
    - pptx.oxml.chart
    - pptx.oxml.dml
    - pptx.oxml.shapes
    - pptx.parts
    - pptx.shapes
    - pptx.text

about:
  home: http://github.com/scanny/python-pptx
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Generate and manipulate Open XML PowerPoint (.pptx) files'
  dev_url: http://github.com/scanny/python-pptx
  doc_url: https://python-pptx.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
