{% set version = "0.6.21" %}

package:
  name: python-pptx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python-pptx/python-pptx-{{ version }}.tar.gz
  sha256: 7798a2aaf89563565b3c7120c0acfe9aff775db0db3580544e3bf4840c2e378f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python =2.7|>=3.6,<3.10
    - pip
    - wheel
  run:
    - python =2.7|>=3.6,<3.10
    - lxml >=3.1.0
    - pillow >=3.3.2
    - xlsxwriter >=0.5.7
    - libiconv

test:
  imports:
    - pptx
    - pptx.chart
    - pptx.compat
    - pptx.dml
    - pptx.enum
    - pptx.opc
    - pptx.oxml
    - pptx.oxml.chart
    - pptx.oxml.dml
    - pptx.oxml.shapes
    - pptx.parts
    - pptx.shapes
    - pptx.text
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/scanny/python-pptx
  license_file: LICENSE
  license: MIT
  license_family: MIT
  license_url: https://github.com/scanny/python-pptx/blob/master/LICENSE
  summary: Generate and manipulate Open XML PowerPoint (.pptx) files
  dev_url: https://github.com/scanny/python-pptx
  doc_url: https://python-pptx.readthedocs.io
  doc_source_url: https://github.com/scanny/python-pptx
  description: python-pptx is a Python library for creating and updating PowerPoint (.pptx) files
extra:
  skip-lints:
    - avoid_noarch
    - invalid_url
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors

