{% set name = "python-pptx" %}
{% set version = "0.6.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 587497ff28e779ab18dbb074f6d4052893c85dedc95ed75df319364f331fedee

build:
  number: 0
  skip: True  # [s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - lxml >=3.1.0
    - pillow >=3.3.2
    - xlsxwriter >=0.5.7

test:
  source_files:
    - tests
  imports:
    - pptx
    - pptx.chart
    - pptx.compat
    - pptx.dml
    - pptx.enum
    - pptx.opc
    - pptx.oxml
    - pptx.oxml.chart
    - pptx.oxml.dml
    - pptx.oxml.shapes
    - pptx.parts
    - pptx.shapes
    - pptx.text
  requires:
    - pip
    - behave >=1.2.5
    - mock >=1.0.1
    - pyparsing >=2.0.1
    - pytest >=2.5

  commands:
    - pip check
    - pytest --fixtures ./tests  -vv

about:
  home: https://github.com/scanny/python-pptx
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Generate and manipulate Open XML PowerPoint (.pptx) files
  description: |
    A typical use would be generating a PowerPoint presentation from dynamic content such as a database query,
    analytics output, or a JSON payload, perhaps in response to an HTTP request and downloading the generated
    PPTX file in response. It runs on any Python capable platform, including macOS and Linux, and does not require
    the PowerPoint application to be installed or licensed.

  dev_url: https://github.com/scanny/python-pptx
  doc_url: https://python-pptx.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
