travis:
  secure:
    BINSTAR_TOKEN: JOI1epOizRlD9Vp8DZd4w0WdAApMU+hT30iX9vYtkKLO9881/EfFjsOsDn96Pv3qY84BRV8SIRFUCebOFSMBRd7dAd4mpR9PQf7d92mJjc8LGj6kieHDsiFaAYyPQrWDRFj0i5Ev2cVQsyGNApi0p13dYIhiJHP7w10cT2KS0wBo7Tq3gIGZOVjFq9FJ8j7ZzkaLPOv/hJ9rxOgbPBpS02U5P+i9OZWUYqHjYm5nJpXwmPAeeD43ZbmAPmYHhp/tfEP0QUnSJb+3gQ5e+KDjWFpGIrGf0L2L9f+PkAlSjrl4g1STYJb3+rKyr3vqVsTEMoKApr1iwBBcX1ncMcwapWiWwgQQsnMrggLJA0/voL4SUH4s1zvZjnp4BAXVFLTXcBvrn37x8dPUMFlbpeyvbThudN9ZNFg4VUVfXVHMMz1tnSbHJgvXVUrjsOhZ5rzsGKwBCAcck1lWKuzxlTCpUL45MlbthWsWujJdwQ6EErTO9yx5PZOj3uz/KWNUZF61casklsbr64YiRR4HL4G67xgQK3efI66PGelbX6fuUV/rJ51Liuq6/fJfrR7ddfdTK8CFq/j+TrSeQDAMHmayW9SXPFEEf2PQ40SZvyq9f+TwvrnghCC4sfu8s7dGmGejfliC5e61OsF3jlHtBZSQwAgHlH8Ec1gB1RfDjR+czeM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
