travis:
  secure:
    BINSTAR_TOKEN: WMVdcpFqVUw3m6wMErTK5/PPFfh4E9FoufJWIEo3zMl7waJ4WcTXu0Hss/txrYsnPd9lla98Cp+bHUmUzSe6P8nf0TEmX4APW2BNyuJ1Y4Id/uLHY7WY+e8YCckumXwtqjcfHhL7X6K5zk8nY22LKj8rR6KiXxq666gl5abBVuRkbkXwgohTjza2rhWVp/y4GmyV2vFk60tgSm8lru0c5psBGS5tch9goxhnxHHiVVaBlQrmJMrUsggEiAbdsnE1uZ4USQS9FnMIonBxEHEgwL7KiOrgavAzHusZ14+GgBFAuiQrU+62rL+LvNMJxV6gPO27rCAlZmFxLqpbrmILcpvUXx45A7vGAkM461Zju50xE2SB85CdokwQiesVHZgYEHczE7hx7TBYkN1Hl39kU0lyVw6tgpbHYQQAhfZA7CSc4+Z98FZGRISO0psmnV+/77KX7hCDWAOuKrBl4Cvi4A+dpP2gXDIwSIzDLK50niscOP8Ezxa0VfkLMimEt+xZKhEhpp9faVe1eS2Hh8SWTcAlt3zdfQH+uwP9H95YnHtG7yjQ8314o8TeZqY/7rrgbVfC6fpUXnRJ00I7uQbhx1jGsA6x+7LrUyiC8TuA5O7jbYry5znySzGtAj7nwd9QkZxQMP3UZSu7CaPPKhcvWB2PP2dU531ClXSESYcXh9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
